Ext.define('OmniDashboard.model.shared.OmniSiteModel', {
    extend: 'OmniDashboard.model.shared.OmniModel',
    fields: [
        { name: 'shopID',type:'auto'},
        { name: 'domainName', type: 'auto' },
        { name: 'linkedin_link',defaultValue:''},
        { name: 'skype_account',defaultValue:''},
        { name: 'telegram_account',defaultValue:''},
        { name: 'whatsapp_account',defaultValue:''},
        { name: 'twitter_link',defaultValue:''},
        { name: 'facebook_link',defaultValue:''},
        { name: 'instagram_link',defaultValue:''},
        { name: 'youtube_link',defaultValue:''},
        { name: 'google_plus_link',defaultValue:''},
        { name: 'pinterest_link',defaultValue:''},
        { name: 'wizardStep', type:'auto',defaultValue:'welcome'},
        { name: 'shopFQDN', type: 'auto' ,defaultValue:""},
        { name: 'shopDefaultSubdomain', type: 'auto' ,defaultValue:""},
        { name: 'shopName', type: 'textrequired', defaultValue:'Minha loja online' },
        { name: 'country', type: 'textrequired',defaultValue:'Brasil' },
        { name: 'zipCode', type: 'textrequired' },
        { name: 'shopOpening',type: 'textrequired'},
        { name: 'state', type: 'textrequired' },
        { name: 'productCategory', defaultValue:'cat-0'},
        { name: 'neighborhood',type: 'textrequired' },
        { name: 'city', type: 'textrequired' },
        { name: 'isOwnerAdmin', type:'bool', defaultValue:false},
        { name: 'isBeneficiente', type:'bool', defaultValue:false},        
        { name: 'suite', type: 'textrequired'},
        { name: 'streetAddressNumber', type: 'textrequired' },
        { name: 'streetAddress', type: 'textrequired' },
        { name: 'shopCNPJ', type: 'textrequired', defaultValue:" " },
        { name: 'shopOwnerCPF', type: 'textrequired', defaultValue:" " },
        { name: 'frontPageAdID', type:'string',defaultValue:""},
        { name: 'frontPageItemID', type:'string',defaultValue:""},
        { name: 'shopSlogan', type: 'textrequired' },
        { name: 'shopDefaultTheme', type: 'auto' ,defaultValue:"default_theme"},
        { name: 'termsOfUseAccepted', type:'bool',defaultValue:false},
        { name: 'shopDefaultThemeVersion', type: 'auto' ,defaultValue:"default_theme"},
        { name: 'shopLogo', type: 'auto', defaultValue:'https://lh3.googleusercontent.com/TAQ4bJwnXNZQ2fiJ21K3k11y3-mcoOKuvTlOKuCtLNMPXAS5mV5YJQZR35KlBXwk2UvinyIOsqXcwfKOCRA'},
        { name: 'shopCurrencySymbol', type: 'auto' },
        { name: 'shopLocale', type: 'auto',defaultValue:'pt_BR' },
        { name: 'shopContactEmail', type: 'textrequired'},
        { name: 'shopContactPhone',type: 'textrequired' },
        { name: 'autoUpdateTemplate', type:'bool'},
        { name: 'isActive', type:'bool'},
        { name: 'readyToOpen', type:'bool'},
        { name: 'loaded', type:'bool', defaultValue:true},
        { name: 'shopContactAddress',type: 'textrequired' },
        { name: 'deliveryZipCode',type: 'textrequired'},
        { name: 'shopNomeEmpresarial',type: 'textrequired'},
        { name: 'shopAboutUs',type: 'textrequired' },
        { name: 'shopDefaultCatalog'},
        { name: 'shopUnderConstructionMessage' },
        { name: 'isVerified', type:'bool' },
        { name: 'hasDomain', type: 'bool', defaultValue:false},
        { name: 'eshopType'},
        { name: 'shopType',type: 'textrequired'},
        { name: 'enableDebug', type:'bool'},
        { name: 'enableShareCatalog', type:'bool' },
        { name: 'enableResaleCatalog', type: 'bool',defaultValue:true },
        { name: 'shareCatalogPrice' },
        { name: 'enableResaleCatalogPrice'},
        { name: 'enableUsed', type: 'bool' },
        { name: 'enableCollectible', type: 'bool' },
        { name: 'enableDomainRedirect', type: 'bool' },
        { name: 'domainRedirectPrice' },
        { name: 'enableSponsorPage', type:'bool'},
        { name: 'shopCNAME'}
    ]
})